--- 
- hosts: 10.0.0.5 
  become: yes
  tasks: 
  - name: i wnat to install git 
    apt: 
     name: git 
     state: present 
    tags: mygit 

  - name: i wnat to install tree 
    apt: 
     name: tree
     state: present 
    tags: mytree 

  - name: i want to install wget 
    apt: 
     name: wget 
     state: present 
    tags: mywget  
    